DELETE  FROM ADOPCIONENTITY;
DELETE FROM CALIFICACIONENTITY;
DELETE FROM CLIENTEENTITY;
DELETE FROM COMPRAENTITY;
DELETE FROM ESPECIEENTITY;
DELETE FROM ESPECIEENTITY_RAZAENTITY;
DELETE FROM HISTORIAENTITY;
DELETE FROM MASCOTAADOPCIONENTITY;
DELETE FROM MASCOTAENTITY;
DELETE FROM MASCOTAVENTAENTITY;
DELETE FROM RAZAENTITY;

